{
 "title": "Работа",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Источник",
    "query": "SELECT title FROM mod_jobs_sources"
   },
   {
    "name": "region",
    "label": "Регион",
    "query": "Минск, Минская обл., Витебская обл., Гродненская обл., Могилевская обл., Гомельская обл., Брестская обл."
   },
   {
    "name": "profession",
    "label": "Профессии",
    "query": "SELECT title FROM mod_jobs_professions"
   },
   {
    "name": "categories",
    "label": "Сферы деятельности",
    "query": "SELECT title FROM mod_jobs_categories"
   }
  ]
 },
 "panels": [
  { "title": "Общее", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Количество активных резюме и вакансий",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT jeva.date_activity AS time,\r\n       COUNT(jeva.id) AS 'Вакансии'\r\nFROM mod_jobs_employers_vacancies_activity AS jeva\r\n  JOIN mod_jobs_employers_vacancies AS jev ON jev.id = jeva.vacancy_id\r\n  JOIN mod_jobs_sources AS js ON js.id = jev.source_id\r\nWHERE $__timeFilter(jeva.date_activity)\r\n  AND js.title = '$source'\r\nGROUP BY jeva.date_activity\r\nORDER BY jeva.date_activity"
    },
    {
     "rawSql": "SELECT jeva.date_activity AS time,\r\n       COUNT(DISTINCT je.title) AS \"Количество раблотодателей с активными вакансиями\"\r\nFROM mod_jobs_employers AS je\r\n    JOIN mod_jobs_employers_vacancies AS jev ON je.id = jev.employer_id\r\n    JOIN mod_jobs_employers_vacancies_activity AS jeva ON jev.id = jeva.vacancy_id\r\n    JOIN mod_jobs_sources AS js ON js.id = jev.source_id\r\nWHERE $__timeFilter(jeva.date_activity)\r\n  AND js.title = '$source'\r\nGROUP BY jeva.date_activity\r\nORDER BY jeva.date_activity;"
    },
    {
     "rawSql": "SELECT jra.date_activity AS time,\n       COUNT(jra.id) AS 'Резюме в активном поиске'\nFROM mod_jobs_resume_activity AS jra\n  JOIN mod_jobs_resume AS jr ON jr.id = jra.resume_id\n  JOIN mod_jobs_sources AS js ON js.id = jr.source_id\nWHERE jr.search_status = 'active'\n  AND $__timeFilter(jra.date_activity)\n  AND js.title = '$source'\nGROUP BY jra.date_activity\nORDER BY jra.date_activity;"
    },
    {
     "rawSql": "SELECT jra.date_activity AS time,\n       COUNT(jra.id) AS 'Резюме рассматривает предложения'\nFROM mod_jobs_resume_activity AS jra\n  JOIN mod_jobs_resume AS jr ON jr.id = jra.resume_id\n  JOIN mod_jobs_sources AS js ON js.id = jr.source_id\nWHERE jr.search_status = 'passive'\n  AND $__timeFilter(jra.date_activity)\n  AND js.title = '$source'\nGROUP BY jra.date_activity\nORDER BY jra.date_activity;"
    }
   ]
  },
  {
   "title": "Зарплаты BYN",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT jra.date_activity AS time,\n       AVG(jra.salary_byn) AS 'Резюме средняя'\nFROM mod_jobs_resume_activity AS jra\n    JOIN mod_jobs_resume AS jr ON jra.resume_id = jr.id\n    JOIN mod_jobs_sources AS js ON js.id = jr.source_id\nWHERE jra.salary_byn >= 100\n  AND js.title = '$source'\n  AND $__timeFilter(jra.date_activity)\nGROUP BY jra.date_activity\nORDER BY jra.date_activity"
    },
    {
     "rawSql": "SELECT jra.date_activity AS time,\n       IF (FLOOR(COUNT(1) / 2) != CEILING(COUNT(1) / 2),\n           REGEXP_SUBSTR(\n               GROUP_CONCAT(jra.salary_byn ORDER BY jra.salary_byn SEPARATOR ','),\n               '[0-9\\.]+', 1, COUNT(1) / 2\n           ) + 0,\n           (\n               REGEXP_SUBSTR(\n                   GROUP_CONCAT(jra.salary_byn ORDER BY jra.salary_byn SEPARATOR ','),\n                   '[0-9\\.]+', 1, (COUNT(1) / 2) - 1)\n               +\n               REGEXP_SUBSTR(\n                   GROUP_CONCAT(jra.salary_byn ORDER BY jra.salary_byn SEPARATOR ','),\n                   '[0-9\\.]+', 1, COUNT(1) / 2 + 1)\n           ) / 2\n       ) AS 'Резюме медиана'\nFROM mod_jobs_resume_activity AS jra\n    JOIN mod_jobs_resume AS jr ON jra.resume_id = jr.id\n    JOIN mod_jobs_sources AS js ON js.id = jr.source_id\nWHERE jra.salary_byn >= 100\n  AND js.title = '$source'\n  AND jra.salary_byn IS NOT NULL\n  AND $__timeFilter(jra.date_activity)\nGROUP BY jra.date_activity\nORDER BY jra.date_activity"
    },
    {
     "rawSql": "SELECT jeva.date_activity AS time,\n       AVG(jeva.salary_min_byn) AS 'Вакансии средняя'\nFROM mod_jobs_employers_vacancies_activity AS jeva\n    JOIN mod_jobs_employers_vacancies AS jev ON jeva.vacancy_id = jev.id\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\nWHERE jeva.salary_min_byn >= 100\n  AND js.title = '$source'\n  AND jeva.salary_min_byn IS NOT NULL\n  AND $__timeFilter(jeva.date_activity)\nGROUP BY jeva.date_activity\nORDER BY jeva.date_activity"
    },
    {
     "rawSql": "SELECT jeva.date_activity AS time,\r\n       IF (FLOOR(COUNT(1) / 2) != CEILING(COUNT(1) / 2),\r\n           REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, COUNT(1) / 2\r\n           ) + 0,\r\n           (\r\n               REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, (COUNT(1) / 2) - 1)\r\n               +\r\n               REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, COUNT(1) / 2 + 1)\r\n           ) / 2\r\n       ) AS 'Вакансии медиана'\r\nFROM mod_jobs_employers_vacancies_activity AS jeva\r\n    JOIN mod_jobs_employers_vacancies AS jev ON jeva.vacancy_id = jev.id\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE jeva.salary_min_byn >= 300\r\n  AND js.title = '$source'\r\n  AND jeva.salary_min_byn IS NOT NULL\r\n  AND $__timeFilter(jeva.date_activity)\r\nGROUP BY jeva.date_activity\r\nORDER BY jeva.date_activity;"
    }
   ]
  },
  {
   "title": "Всего активных резюме и вакансий",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT jeva.date_activity AS time,\r\n       COUNT(jeva.id) AS 'Вакансии'\r\nFROM mod_jobs_employers_vacancies_activity AS jeva\r\n  JOIN mod_jobs_employers_vacancies AS jev ON jev.id = jeva.vacancy_id\r\n  JOIN mod_jobs_sources AS js ON js.id = jev.source_id\r\nWHERE $__timeFilter(jeva.date_activity)\r\n  AND js.title = '$source'\r\nGROUP BY jeva.date_activity\r\nORDER BY jeva.date_activity"
    },
    {
     "rawSql": "SELECT jra.date_activity AS time,\n       COUNT(jra.id) AS 'Резюме'\nFROM mod_jobs_resume_activity AS jra\n  JOIN mod_jobs_resume AS jr ON jr.id = jra.resume_id\n  JOIN mod_jobs_sources AS js ON js.id = jr.source_id\nWHERE $__timeFilter(jra.date_activity)\n  AND js.title = '$source'\nGROUP BY jra.date_activity\nORDER BY jra.date_activity;"
    }
   ]
  },
  {
   "title": "Зарплаты BYN по районам [медиана]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT jeva.date_activity AS time,\r\n       IF (FLOOR(COUNT(1) / 2) != CEILING(COUNT(1) / 2),\r\n           REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, COUNT(1) / 2\r\n           ) + 0,\r\n           (\r\n               REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, (COUNT(1) / 2) - 1)\r\n               +\r\n               REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, COUNT(1) / 2 + 1)\r\n           ) / 2\r\n       ) AS 'Вакансии медиана',\r\n       jev.region\r\nFROM mod_jobs_employers_vacancies_activity AS jeva\r\n    JOIN mod_jobs_employers_vacancies AS jev ON jev.id = jeva.vacancy_id\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND jeva.salary_min_byn IS NOT NULL\r\n  AND jeva.salary_min_byn >= 100\r\n  AND $__timeFilter(jeva.date_activity)\r\nGROUP BY jeva.date_activity, jev.region\r\nORDER BY jeva.date_activity;"
    }
   ]
  },
  {
   "title": "Средний возраст в резюме",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT jrs.date_activity AS time,\r\n       AVG(jr.age) AS 'Средний возраст'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_resume_activity AS jrs ON jr.id = jrs.resume_id\r\n    JOIN mod_jobs_sources AS js ON js.id = jr.source_id\r\nWHERE js.title = '$source'\r\n  AND $__timeFilter(jrs.date_activity)\r\nGROUP BY jrs.date_activity\r\nORDER BY jrs.date_activity;"
    }
   ]
  },
  {
   "title": "Зарплаты в вакансиях",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       'до 500 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND jev.salary_min_byn < 500\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       '500 - 1000 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND (jev.salary_min_byn >= 500 AND jev.salary_min_byn < 1000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       '1000 - 2000 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND (jev.salary_min_byn >= 1000 AND jev.salary_min_byn < 2000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       '2000 - 3000 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND (jev.salary_min_byn >= 2000 AND jev.salary_min_byn < 3000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       '3000 - 5000 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND (jev.salary_min_byn >= 3000 AND jev.salary_min_byn < 5000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       'от 5000 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND jev.salary_min_byn >= 5000\r\nORDER BY 2 DESC;"
    }
   ]
  },
  {
   "title": "Зарплаты в резюме",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       'до 500 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND jr.salary_byn < 500\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       '500 - 1000 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND (jr.salary_byn >= 500 AND jr.salary_byn < 1000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       '1000 - 2000 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND (jr.salary_byn >= 1000 AND jr.salary_byn < 2000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       '2000 - 3000 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND (jr.salary_byn >= 2000 AND jr.salary_byn < 3000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       '3000 - 5000 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND (jr.salary_byn >= 3000 AND jr.salary_byn < 5000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       'от 5000 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND jr.salary_byn >= 5000\r\nORDER BY 2 DESC;"
    }
   ]
  },
  {
   "title": "Top 30 резюме (по количеству, средняя зп)",
   "type": "piechart",
   "description": "Указана средняя зарплата",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(jr.title) AS count,\r\n       CONCAT(jr.title, ' - ', ROUND(AVG(jr.salary_byn)), ' byn')\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_resume_activity AS jra ON jra.resume_id = jr.id\r\n    JOIN mod_jobs_sources AS js ON js.id = jr.source_id\r\nWHERE js.title = '$source'\r\n  AND jr.date_close IS NULL\r\nGROUP BY REPLACE(jr.title, '-', '')\r\nORDER BY 2 DESC\r\nLIMIT 30;"
    }
   ]
  },
  {
   "title": "Top 30 вакансий (по количеству, средняя зп)",
   "type": "piechart",
   "description": "Указана средняя зарплата",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(jev.title) AS count,\r\n       CONCAT(jev.title, ' - ', ROUND(AVG(jev.salary_min_byn)), ' byn')\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_employers_vacancies_activity AS jeva ON jeva.vacancy_id = jev.id\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND jev.date_close IS NULL\r\nGROUP BY REPLACE(jev.title, '-', '')\r\nORDER BY 2 DESC\r\nLIMIT 30;"
    }
   ]
  },
  {
   "title": "Зарплата в резюме [медиана]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT jra.date_activity AS time,\r\n       IF (FLOOR(COUNT(1) / 2) != CEILING(COUNT(1) / 2),\r\n           REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jra.salary_byn ORDER BY jra.salary_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, COUNT(1) / 2\r\n               ) + 0,\r\n           (\r\n                   REGEXP_SUBSTR(\r\n                           GROUP_CONCAT(jra.salary_byn ORDER BY jra.salary_byn SEPARATOR ','),\r\n                           '[0-9\\.]+', 1, (COUNT(1) / 2) - 1)\r\n                   +\r\n                   REGEXP_SUBSTR(\r\n                           GROUP_CONCAT(jra.salary_byn ORDER BY jra.salary_byn SEPARATOR ','),\r\n                           '[0-9\\.]+', 1, COUNT(1) / 2 + 1)\r\n               ) / 2\r\n           ) AS 'Количество',\r\n       jp.title\r\nFROM mod_jobs_resume_activity AS jra\r\n    JOIN mod_jobs_resume_professions AS jrp ON jrp.resume_id = jra.resume_id\r\n    JOIN mod_jobs_professions AS jp ON jrp.profession_id = jp.id\r\n    JOIN mod_jobs_resume AS jr ON jr.id = jra.resume_id\r\n    JOIN mod_jobs_sources AS js ON js.id = jr.source_id\r\nWHERE jra.salary_byn IS NOT NULL\r\n  AND js.title = '$source'\r\n  AND $__timeFilter(jra.date_activity)\r\nGROUP BY jra.date_activity, jp.name\r\nORDER BY jra.date_activity"
    }
   ]
  },
  {
   "title": "Зарплата в вакансиях [медиана]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT jeva.date_activity AS time,\r\n       IF (FLOOR(COUNT(1) / 2) != CEILING(COUNT(1) / 2),\r\n           REGEXP_SUBSTR(\r\n               GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n               '[0-9\\.]+', 1, COUNT(1) / 2\r\n           ) + 0,\r\n           (\r\n               REGEXP_SUBSTR(\r\n                       GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                       '[0-9\\.]+', 1, (COUNT(1) / 2) - 1)\r\n               +\r\n               REGEXP_SUBSTR(\r\n                       GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                       '[0-9\\.]+', 1, COUNT(1) / 2 + 1)\r\n           ) / 2\r\n       ) AS 'Количество',\r\n       jp.title\r\nFROM mod_jobs_employers_vacancies_activity AS jeva\r\n    JOIN mod_jobs_employers_vacancies AS jev ON jeva.vacancy_id = jev.id\r\n    JOIN mod_jobs_employers_vacancies_professions AS jevp ON jev.id = jevp.vacancy_id\r\n    JOIN mod_jobs_professions AS jp ON jevp.profession_id = jp.id\r\n    JOIN mod_jobs_sources AS js ON js.id = jev.source_id\r\nWHERE jeva.salary_min_byn IS NOT NULL\r\n  AND js.title = '$source'\r\n  AND $__timeFilter(jeva.date_activity)\r\nGROUP BY jeva.date_activity, jp.name\r\nORDER BY jeva.date_activity;"
    }
   ]
  },
  {
   "title": "Всего вакансий [по заявлению источника]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT js.date_summary AS time,\r\n       js.total_vacancies AS \"Всего вакансий\"\r\nFROM mod_jobs_summary AS js\r\n    JOIN mod_jobs_sources AS js2 ON js.source_id = js2.id\r\nWHERE js2.title = '$source'\r\n  AND $__timeFilter(js.date_summary)\r\nGROUP BY js.date_summary\r\nORDER BY js.date_summary;"
    }
   ]
  },
  {
   "title": "Всего резюме [по заявлению источника]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT js.date_summary AS time,\r\n       js.total_resume AS \"Всего резюме\"\r\nFROM mod_jobs_summary AS js\r\n    JOIN mod_jobs_sources AS js2 ON js.source_id = js2.id\r\nWHERE js2.title = '$source'\r\n  AND $__timeFilter(js.date_summary)\r\nGROUP BY js.date_summary\r\nORDER BY js.date_summary;"
    }
   ]
  },
  {
   "title": "Всего работодателей [по заявлению источника]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT js.date_summary AS time,\r\n       js.total_employers AS \"Всего работодателей\"\r\nFROM mod_jobs_summary AS js\r\n    JOIN mod_jobs_sources AS js2 ON js.source_id = js2.id\r\nWHERE js2.title = '$source'\r\n  AND $__timeFilter(js.date_summary)\r\nGROUP BY js.date_summary\r\nORDER BY js.date_summary;"
    }
   ]
  },
  {
   "title": "Отправлено приглашений в неделю [по заявлению источника]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT js.date_summary AS time,\r\n       js.total_week_invites AS \"Отправлено приглашений в неделю\"\r\nFROM mod_jobs_summary AS js\r\n    JOIN mod_jobs_sources AS js2 ON js.source_id = js2.id\r\nWHERE js2.title = '$source'\r\n  AND $__timeFilter(js.date_summary)\r\nGROUP BY js.date_summary\r\nORDER BY js.date_summary;"
    }
   ]
  },
  { "title": "Профессия: $profession", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }, "repeat": "profession" },
  {
   "title": "Людей в резюме",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT jps.date_summary AS time,\r\n       jps.total_people AS \"Количество\"\r\nFROM mod_jobs_professions_summary AS jps\r\n    JOIN mod_jobs_sources AS js ON js.id = jps.source_id\r\n    JOIN mod_jobs_professions AS jp ON jps.profession_id = jp.id\r\nWHERE $__timeFilter(jps.date_summary)\r\n  AND js.title = '$source'\r\n  AND jp.title = $profession\r\nGROUP BY jps.date_summary, jp.name\r\nORDER BY jps.date_summary;"
    }
   ]
  },
  {
   "title": "Вакансии / резюме",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT jeva.date_activity AS time,\r\n       COUNT(jeva.id) AS 'Вакансии'\r\nFROM mod_jobs_employers_vacancies_activity AS jeva\r\n    JOIN mod_jobs_employers_vacancies AS jev ON jev.id = jeva.vacancy_id\r\n    JOIN mod_jobs_sources AS js ON js.id = jev.source_id\r\nWHERE $__timeFilter(jeva.date_activity)\r\n  AND js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_employers_vacancies_professions AS jevp\r\n           JOIN mod_jobs_professions AS jp ON jevp.profession_id = jp.id\r\n       WHERE jevp.vacancy_id = jeva.vacancy_id\r\n         AND jp.title = $profession)\r\nGROUP BY jeva.date_activity\r\nORDER BY jeva.date_activity"
    },
    {
     "rawSql": "SELECT jra.date_activity AS time,\n       COUNT(jra.id) AS 'Резюме в активном поиске'\nFROM mod_jobs_resume_activity AS jra\n    JOIN mod_jobs_resume AS jr ON jr.id = jra.resume_id\n    JOIN mod_jobs_sources AS js ON js.id = jr.source_id\nWHERE jr.search_status = 'active'\n  AND js.title = '$source'\n  AND $__timeFilter(jra.date_activity)\n  AND (SELECT 1\n       FROM mod_jobs_resume_professions AS jrp\n           JOIN mod_jobs_professions AS jp ON jrp.profession_id = jp.id\n       WHERE jrp.resume_id = jra.resume_id\n         AND jp.title = $profession)\nGROUP BY jra.date_activity\nORDER BY jra.date_activity;"
    },
    {
     "rawSql": "SELECT jra.date_activity AS time,\n       COUNT(jra.id) AS 'Резюме рассматривает предложения'\nFROM mod_jobs_resume_activity AS jra\n    JOIN mod_jobs_resume AS jr ON jr.id = jra.resume_id\n    JOIN mod_jobs_sources AS js ON js.id = jr.source_id\nWHERE jr.search_status = 'passive'\n  AND js.title = '$source'\n  AND $__timeFilter(jra.date_activity)\n  AND (SELECT 1\n       FROM mod_jobs_resume_professions AS jrp\n           JOIN mod_jobs_professions AS jp ON jrp.profession_id = jp.id\n       WHERE jrp.resume_id = jra.resume_id\n         AND jp.title = $profession)\nGROUP BY jra.date_activity\nORDER BY jra.date_activity;"
    }
   ]
  },
  {
   "title": "Зарплаты в вакансиях",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       'до 500 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_employers_vacancies_professions AS jevp\r\n           JOIN mod_jobs_professions AS jp ON jevp.profession_id = jp.id\r\n       WHERE jevp.vacancy_id = jev.id\r\n         AND jp.title = $profession)\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND jev.salary_min_byn < 500\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       '500 - 1000 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_employers_vacancies_professions AS jevp\r\n           JOIN mod_jobs_professions AS jp ON jevp.profession_id = jp.id\r\n       WHERE jevp.vacancy_id = jev.id\r\n         AND jp.title = $profession)\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND (jev.salary_min_byn >= 500 AND jev.salary_min_byn < 1000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       '1000 - 2000 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_employers_vacancies_professions AS jevp\r\n           JOIN mod_jobs_professions AS jp ON jevp.profession_id = jp.id\r\n       WHERE jevp.vacancy_id = jev.id\r\n         AND jp.title = $profession)\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND (jev.salary_min_byn >= 1000 AND jev.salary_min_byn < 2000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       '2000 - 3000 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_employers_vacancies_professions AS jevp\r\n           JOIN mod_jobs_professions AS jp ON jevp.profession_id = jp.id\r\n       WHERE jevp.vacancy_id = jev.id\r\n         AND jp.title = $profession)\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND (jev.salary_min_byn >= 2000 AND jev.salary_min_byn < 3000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       '3000 - 5000 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_employers_vacancies_professions AS jevp\r\n           JOIN mod_jobs_professions AS jp ON jevp.profession_id = jp.id\r\n       WHERE jevp.vacancy_id = jev.id\r\n         AND jp.title = $profession)\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND (jev.salary_min_byn >= 3000 AND jev.salary_min_byn < 5000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       'от 5000 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_employers_vacancies_professions AS jevp\r\n           JOIN mod_jobs_professions AS jp ON jevp.profession_id = jp.id\r\n       WHERE jevp.vacancy_id = jev.id\r\n         AND jp.title = $profession)\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND jev.salary_min_byn >= 5000\r\nORDER BY 2 DESC;"
    }
   ]
  },
  {
   "title": "Зарплаты в резюме",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       'до 500 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_resume_professions AS jrp\r\n           JOIN mod_jobs_professions AS jp ON jrp.profession_id = jp.id\r\n       WHERE jrp.resume_id = jr.id\r\n         AND jp.title = $profession)\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND jr.salary_byn < 500\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       '500 - 1000 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_resume_professions AS jrp\r\n           JOIN mod_jobs_professions AS jp ON jrp.profession_id = jp.id\r\n       WHERE jrp.resume_id = jr.id\r\n         AND jp.title = $profession)\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND (jr.salary_byn >= 500 AND jr.salary_byn < 1000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       '1000 - 2000 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_resume_professions AS jrp\r\n           JOIN mod_jobs_professions AS jp ON jrp.profession_id = jp.id\r\n       WHERE jrp.resume_id = jr.id\r\n         AND jp.title = $profession)\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND (jr.salary_byn >= 1000 AND jr.salary_byn < 2000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       '2000 - 3000 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_resume_professions AS jrp\r\n           JOIN mod_jobs_professions AS jp ON jrp.profession_id = jp.id\r\n       WHERE jrp.resume_id = jr.id\r\n         AND jp.title = $profession)\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND (jr.salary_byn >= 2000 AND jr.salary_byn < 3000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       '3000 - 5000 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_resume_professions AS jrp\r\n           JOIN mod_jobs_professions AS jp ON jrp.profession_id = jp.id\r\n       WHERE jrp.resume_id = jr.id\r\n         AND jp.title = $profession)\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND (jr.salary_byn >= 3000 AND jr.salary_byn < 5000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       'от 5000 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_resume_professions AS jrp\r\n           JOIN mod_jobs_professions AS jp ON jrp.profession_id = jp.id\r\n       WHERE jrp.resume_id = jr.id\r\n         AND jp.title = $profession)\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND jr.salary_byn >= 5000\r\nORDER BY 2 DESC;"
    }
   ]
  },
  {
   "title": "Зарплата",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT jra.date_activity AS time,\n       IF (FLOOR(COUNT(1) / 2) != CEILING(COUNT(1) / 2),\n           REGEXP_SUBSTR(\n               GROUP_CONCAT(jra.salary_byn ORDER BY jra.salary_byn SEPARATOR ','),\n               '[0-9\\.]+', 1, COUNT(1) / 2\n           ) + 0,\n           (\n               REGEXP_SUBSTR(\n                   GROUP_CONCAT(jra.salary_byn ORDER BY jra.salary_byn SEPARATOR ','),\n                   '[0-9\\.]+', 1, (COUNT(1) / 2) - 1)\n               +\n               REGEXP_SUBSTR(\n                   GROUP_CONCAT(jra.salary_byn ORDER BY jra.salary_byn SEPARATOR ','),\n                   '[0-9\\.]+', 1, COUNT(1) / 2 + 1)\n           ) / 2\n       ) AS 'Резюме медиана'\nFROM mod_jobs_resume_activity AS jra\n    JOIN mod_jobs_resume AS jr ON jr.id = jra.resume_id\n    JOIN mod_jobs_sources AS js ON js.id = jr.source_id\nWHERE jra.salary_byn IS NOT NULL\n  AND $__timeFilter(jra.date_activity)\n  AND js.title = '$source'\n  AND (SELECT 1\n       FROM mod_jobs_resume_professions AS jrp\n            JOIN mod_jobs_professions AS jp ON jrp.profession_id = jp.id\n       WHERE jrp.resume_id = jra.resume_id\n         AND jp.title = $profession)\nGROUP BY jra.date_activity\nORDER BY jra.date_activity"
    },
    {
     "rawSql": "SELECT jeva.date_activity AS time,\r\n       IF (FLOOR(COUNT(1) / 2) != CEILING(COUNT(1) / 2),\r\n           REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, COUNT(1) / 2\r\n           ) + 0,\r\n           (\r\n               REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, (COUNT(1) / 2) - 1)\r\n               +\r\n               REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, COUNT(1) / 2 + 1)\r\n           ) / 2\r\n       ) AS 'Вакансии медиана'\r\nFROM mod_jobs_employers_vacancies_activity AS jeva\r\n    JOIN mod_jobs_employers_vacancies AS jev ON jev.id = jeva.vacancy_id\r\n    JOIN mod_jobs_sources AS js ON js.id = jev.source_id\r\nWHERE jeva.salary_min_byn IS NOT NULL\r\n  AND js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_employers_vacancies_professions AS jevp\r\n            JOIN mod_jobs_professions AS jp ON jevp.profession_id = jp.id\r\n       WHERE jevp.vacancy_id = jeva.vacancy_id\r\n         AND jp.title = $profession)\r\nGROUP BY jeva.date_activity\r\nORDER BY jeva.date_activity;"
    },
    {
     "rawSql": "SELECT jeva.date_activity AS time,\r\n       IF (FLOOR(COUNT(1) / 2) != CEILING(COUNT(1) / 2),\r\n           REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, COUNT(1) / 2\r\n           ) + 0,\r\n           (\r\n               REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, (COUNT(1) / 2) - 1)\r\n               +\r\n               REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, COUNT(1) / 2 + 1)\r\n           ) / 2\r\n       ) AS 'Вакансии медиана общее'\r\nFROM mod_jobs_employers_vacancies_activity AS jeva\r\n    JOIN mod_jobs_employers_vacancies AS jev ON jeva.vacancy_id = jev.id\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE jeva.salary_min_byn IS NOT NULL\r\n  AND js.title = '$source'\r\n  AND $__timeFilter(jeva.date_activity)\r\nGROUP BY jeva.date_activity\r\nORDER BY jeva.date_activity;"
    }
   ]
  },
  {
   "title": "Сфера деятельности: $categories",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "repeat": "categories"
  },
  {
   "title": "Вакансии / резюме",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT jeva.date_activity AS time,\r\n       COUNT(jeva.id) AS 'Вакансии'\r\nFROM mod_jobs_employers_vacancies_activity AS jeva\r\nWHERE $__timeFilter(jeva.date_activity)\r\n  AND (SELECT 1\r\n       FROM mod_jobs_employers_vacancies_categories AS jevc\r\n           JOIN mod_jobs_categories AS jc ON jevc.category_id = jc.id\r\n       WHERE jevc.vacancy_id = jeva.vacancy_id\r\n         AND jc.title = $categories)\r\nGROUP BY jeva.date_activity\r\nORDER BY jeva.date_activity;"
    },
    {
     "rawSql": "SELECT jra.date_activity AS time,\r\n       COUNT(jra.id) AS 'Резюме в активном поиске'\r\nFROM mod_jobs_resume_activity AS jra\r\n    JOIN mod_jobs_resume AS jr ON jr.id = jra.resume_id\r\nWHERE jr.search_status = 'active'\r\n  AND $__timeFilter(jra.date_activity)\r\n  AND (SELECT 1\r\n       FROM mod_jobs_resume_categories AS jrc\r\n           JOIN mod_jobs_categories AS jc ON jrc.category_id = jc.id\r\n       WHERE jrc.resume_id = jra.resume_id\r\n         AND jc.title = $categories)\r\nGROUP BY jra.date_activity\r\nORDER BY jra.date_activity;"
    },
    {
     "rawSql": "SELECT jra.date_activity AS time,\r\n       COUNT(jra.id) AS 'Резюме рассматривает предложения'\r\nFROM mod_jobs_resume_activity AS jra\r\n    JOIN mod_jobs_resume AS jr ON jr.id = jra.resume_id\r\nWHERE jr.search_status = 'passive'\r\n  AND $__timeFilter(jra.date_activity)\r\n  AND (SELECT 1\r\n       FROM mod_jobs_resume_categories AS jrc\r\n           JOIN mod_jobs_categories AS jc ON jrc.category_id = jc.id\r\n       WHERE jrc.resume_id = jra.resume_id\r\n         AND jc.title = $categories)\r\nGROUP BY jra.date_activity\r\nORDER BY jra.date_activity;"
    }
   ]
  },
  {
   "title": "Зарплаты в вакансиях",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       'до 500 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_employers_vacancies_categories AS jevc\r\n           JOIN mod_jobs_categories AS jc ON jevc.category_id = jc.id\r\n       WHERE jevc.vacancy_id = jev.id\r\n         AND jc.title = $categories)\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND jev.salary_min_byn < 500\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       '500 - 1000 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_employers_vacancies_categories AS jevc\r\n           JOIN mod_jobs_categories AS jc ON jevc.category_id = jc.id\r\n       WHERE jevc.vacancy_id = jev.id\r\n         AND jc.title = $categories)\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND (jev.salary_min_byn >= 500 AND jev.salary_min_byn < 1000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       '1000 - 2000 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_employers_vacancies_categories AS jevc\r\n           JOIN mod_jobs_categories AS jc ON jevc.category_id = jc.id\r\n       WHERE jevc.vacancy_id = jev.id\r\n         AND jc.title = $categories)\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND (jev.salary_min_byn >= 1000 AND jev.salary_min_byn < 2000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       '2000 - 3000 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_employers_vacancies_categories AS jevc\r\n           JOIN mod_jobs_categories AS jc ON jevc.category_id = jc.id\r\n       WHERE jevc.vacancy_id = jev.id\r\n         AND jc.title = $categories)\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND (jev.salary_min_byn >= 2000 AND jev.salary_min_byn < 3000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       '3000 - 5000 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_employers_vacancies_categories AS jevc\r\n           JOIN mod_jobs_categories AS jc ON jevc.category_id = jc.id\r\n       WHERE jevc.vacancy_id = jev.id\r\n         AND jc.title = $categories)\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND (jev.salary_min_byn >= 3000 AND jev.salary_min_byn < 5000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jev.id) AS count,\r\n       'от 5000 BYN'\r\nFROM mod_jobs_employers_vacancies AS jev\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_employers_vacancies_categories AS jevc\r\n           JOIN mod_jobs_categories AS jc ON jevc.category_id = jc.id\r\n       WHERE jevc.vacancy_id = jev.id\r\n         AND jc.title = $categories)\r\n  AND jev.date_close IS NULL\r\n  AND jev.salary_min_byn IS NOT NULL\r\n  AND jev.salary_min_byn >= 5000\r\nORDER BY 2 DESC;"
    }
   ]
  },
  {
   "title": "Зарплаты в резюме",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       'до 500 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_resume_categories AS jrc\r\n           JOIN mod_jobs_categories AS jc ON jrc.category_id = jc.id\r\n       WHERE jrc.resume_id = jr.id\r\n         AND jc.title = $categories)\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND jr.salary_byn < 500\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       '500 - 1000 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_resume_categories AS jrc\r\n           JOIN mod_jobs_categories AS jc ON jrc.category_id = jc.id\r\n       WHERE jrc.resume_id = jr.id\r\n         AND jc.title = $categories)\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND (jr.salary_byn >= 500 AND jr.salary_byn < 1000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       '1000 - 2000 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_resume_categories AS jrc\r\n           JOIN mod_jobs_categories AS jc ON jrc.category_id = jc.id\r\n       WHERE jrc.resume_id = jr.id\r\n         AND jc.title = $categories)\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND (jr.salary_byn >= 1000 AND jr.salary_byn < 2000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       '2000 - 3000 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_resume_categories AS jrc\r\n           JOIN mod_jobs_categories AS jc ON jrc.category_id = jc.id\r\n       WHERE jrc.resume_id = jr.id\r\n         AND jc.title = $categories)\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND (jr.salary_byn >= 2000 AND jr.salary_byn < 3000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       '3000 - 5000 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_resume_categories AS jrc\r\n           JOIN mod_jobs_categories AS jc ON jrc.category_id = jc.id\r\n       WHERE jrc.resume_id = jr.id\r\n         AND jc.title = $categories)\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND (jr.salary_byn >= 3000 AND jr.salary_byn < 5000)\r\nORDER BY 2 DESC;"
    },
    {
     "rawSql": "SELECT NOW() AS time,\r\n       count(DISTINCT jr.id) AS count,\r\n       'от 5000 BYN'\r\nFROM mod_jobs_resume AS jr\r\n    JOIN mod_jobs_sources AS js ON jr.source_id = js.id\r\nWHERE js.title = '$source'\r\n  AND (SELECT 1\r\n       FROM mod_jobs_resume_categories AS jrc\r\n           JOIN mod_jobs_categories AS jc ON jrc.category_id = jc.id\r\n       WHERE jrc.resume_id = jr.id\r\n         AND jc.title = $categories)\r\n  AND jr.date_close IS NULL\r\n  AND jr.salary_byn IS NOT NULL\r\n  AND jr.salary_byn >= 5000\r\nORDER BY 2 DESC;"
    }
   ]
  },
  {
   "title": "Зарплата",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT jra.date_activity AS time,\n       IF (FLOOR(COUNT(1) / 2) != CEILING(COUNT(1) / 2),\n           REGEXP_SUBSTR(\n               GROUP_CONCAT(jra.salary_byn ORDER BY jra.salary_byn SEPARATOR ','),\n               '[0-9\\.]+', 1, COUNT(1) / 2\n           ) + 0,\n           (\n               REGEXP_SUBSTR(\n                   GROUP_CONCAT(jra.salary_byn ORDER BY jra.salary_byn SEPARATOR ','),\n                   '[0-9\\.]+', 1, (COUNT(1) / 2) - 1)\n               +\n               REGEXP_SUBSTR(\n                   GROUP_CONCAT(jra.salary_byn ORDER BY jra.salary_byn SEPARATOR ','),\n                   '[0-9\\.]+', 1, COUNT(1) / 2 + 1)\n           ) / 2\n       ) AS 'Резюме медиана'\nFROM mod_jobs_resume_activity AS jra\nWHERE jra.salary_byn IS NOT NULL\n  AND $__timeFilter(jra.date_activity)\n  AND (SELECT 1\n       FROM mod_jobs_resume_categories AS jrc\n            JOIN mod_jobs_categories AS jc ON jrc.category_id = jc.id\n       WHERE jrc.resume_id = jra.resume_id\n         AND jc.title = $categories)\nGROUP BY jra.date_activity\nORDER BY jra.date_activity"
    },
    {
     "rawSql": "SELECT jeva.date_activity AS time,\r\n       IF (FLOOR(COUNT(1) / 2) != CEILING(COUNT(1) / 2),\r\n           REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, COUNT(1) / 2\r\n           ) + 0,\r\n           (\r\n               REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, (COUNT(1) / 2) - 1)\r\n               +\r\n               REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, COUNT(1) / 2 + 1)\r\n           ) / 2\r\n       ) AS 'Вакансии медиана'\r\nFROM mod_jobs_employers_vacancies_activity AS jeva\r\nWHERE jeva.salary_min_byn IS NOT NULL\r\n  AND (SELECT 1\r\n       FROM mod_jobs_employers_vacancies_categories AS jevc\r\n            JOIN mod_jobs_categories AS jc ON jevc.category_id = jc.id\r\n       WHERE jevc.vacancy_id = jeva.vacancy_id\r\n         AND jc.title = $categories)\r\nGROUP BY jeva.date_activity\r\nORDER BY jeva.date_activity;"
    },
    {
     "rawSql": "SELECT jeva.date_activity AS time,\r\n       IF (FLOOR(COUNT(1) / 2) != CEILING(COUNT(1) / 2),\r\n           REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, COUNT(1) / 2\r\n           ) + 0,\r\n           (\r\n               REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, (COUNT(1) / 2) - 1)\r\n               +\r\n               REGEXP_SUBSTR(\r\n                   GROUP_CONCAT(jeva.salary_min_byn ORDER BY jeva.salary_min_byn SEPARATOR ','),\r\n                   '[0-9\\.]+', 1, COUNT(1) / 2 + 1)\r\n           ) / 2\r\n       ) AS 'Вакансии медиана общее'\r\nFROM mod_jobs_employers_vacancies_activity AS jeva\r\n    JOIN mod_jobs_employers_vacancies AS jev ON jeva.vacancy_id = jev.id\r\n    JOIN mod_jobs_sources AS js ON jev.source_id = js.id\r\nWHERE jeva.salary_min_byn IS NOT NULL\r\n  AND js.title = '$source'\r\n  AND $__timeFilter(jeva.date_activity)\r\nGROUP BY jeva.date_activity\r\nORDER BY jeva.date_activity;"
    }
   ]
  }
 ]
}